name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install dev dependencies
        run: npm install

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Set up rust cache
        uses: Swatinem/rust-cache@v1

      - name: Save git SHA for Foundry
        run: |
          echo "forge-sha=$(git ls-remote  https://github.com/gakonst/foundry HEAD | awk '{ print $1}')" >> $GITHUB_ENV

      - name: Cache Forge
        uses: actions/cache@v2
        id: cache-forge
        env:
          cache-name: cache-forge
        with:
          path: ~/.cargo/bin/forge
          key: ${{ env.cache-name }}-${{ env.forge-sha }}

      # if couldn't get, install it
      - name: Install Forge
        if: steps.cache-forge.outputs.cache-hit != 'true'
        run: |
          cargo install --git https://github.com/gakonst/foundry --bin forge --locked

      - name: Pull Submodules
        run: forge update

      - name: Run lint check
        run: npm run lint:check

      - name: Run tests
        run: forge test